wiki/encyclopedia/urls.py
from django.urls import path  
from . import views
app_name = 'encyclopedia'
urlpatterns = [
    path("",views.index, name = "index"),
    path("search", views.search, name = "search"),
    path("create", views.create, name = "create"),
    path("edit/<str:title>/",views.edit, name = "edit"),
    path("random",views.random, name = "random"),
    path("<str:entry>",views.entry ,name = "entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("wiki/", include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
markdowner = Markdown()
# Create your views here.

from . import util
from django import forms

class Search_form(forms.Form):
    query = forms.CharField(label = 'Search Encyclopedia')

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })
def entry(request,entry):
    content = util.get_entry(entry)
    if content != None:
        return render(request, "encyclopedia/entry.html", {
        "entrie": markdowner.convert(content),
        'title':entry
    })
    else:
        return render(request, "encyclopedia/index.html", {
                "entries": None,
                 "message" :None
                
            })


def search(request):
    if request.method == "POST":
        query = request.POST.get("query").strip() if request.POST.get("query") else None

        if query:
            result, Flag = util.search(query)

            if Flag:
                content = util.get_entry(result)
                return render(request, "encyclopedia/entry.html", {
                    "entrie": markdowner.convert(content),
                    "title":query
                })
            elif not Flag:
                return render(request, "encyclopedia/index.html", {
                    "entries": result,
                    "message" :Flag,
                    "title":query

                })
            else:
                content = result
                return render(request, "encyclopedia/entry.html", {
                    "entrie": markdowner.convert(content),
                    "title":query
                })
        else:
            return render(request, "encyclopedia/index.html", {
                "entries": util.list_entries(),
                 "message" :Flag,
                 "title":query
                
            })

def create(request):
  
    if request.method == "POST":
        title = request.POST.get("title").strip() if request.POST.get("title") else ""
        content = request.POST.get("content").strip() if request.POST.get("content") else ""
        Flag = util.save_entry(title,content)
        if Flag == True:
            content = util.get_entry(title)
            return render(request, "encyclopedia/entry.html", {
                "entrie": markdowner.convert(content),
                "message":Flag,
                "title":title
                })
        else:
       
            return render(request, "encyclopedia/create.html", {
                "message": Flag
                })
    else:
    
        return render(request, "encyclopedia/create.html", {
            "edit":False,
            })
    
def edit(request,title):
    if request.method == "POST":
        content = request.POST.get("content").strip() if request.POST.get("content") else ""  
        util.Edit_entry(title,content)
        return render(request, "encyclopedia/entry.html", {
                "entrie": markdowner.convert(content),
                "message":True,
                "title":title
                })
        
    else:
        content = util.get_entry(title)
        return render(request, "encyclopedia/create.html",{
            "edit" :True,
            "title":title,
            "content":content

        })
    
def random(request):
    title = util.give_random()
    content = util.get_entry(title)
    return render(request, "encyclopedia/entry.html", {
        "entrie": markdowner.convert(content),
        'title':title
    })

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if edit == False %}
    <h2 >Add Entry</h2>
    {% else %}
    <h2 >Edit Entry</h2>
    {% endif %}
    {% if message == False %}
        <p class="alert alert-warning" role="alert">Please Enter valid title</p>
    {% endif %}
    {% if edit == True%}
    <form action="{% url 'encyclopedia:edit' title=title %}", method = 'post'>
    {% else %}
    <form action="{% url 'encyclopedia:create' %}", method = 'post'>
    {% endif %}
        {% csrf_token %}
        <div class="mb-3">
            {% if edit == True %}
            <label for="title" class="form-label">{{title}}</label>
            {% else %}
            <label for="title" class="form-label">Enter title</label>
            <input type="text" class="form-control" name = "title" id="title" placeholder="Enter Title">
            {% endif %}
          </div>
        <div class="mb-3" >
            {% if edit == True %}
            <label for="content" class="form-label">Edit the content Here:</label>
            {% else %}
            <label for="content" class="form-label">Write the content Here:</label>
            {% endif %}
            <textarea id="content" class="form-control" name="content" rows="4" cols="50">{{content}}</textarea>
            </div>
        <input type  = "submit" class="btn btn-primary mb-3">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if message == True %}
    <p class="alert alert-success" role="alert">Sucessfully Saved your entrie</p>
    {% endif %}
    {% if entrie != None %}
    {{ entrie | safe }}
    {% else %}
    <p class="alert alert-info" role="alert">Page does Not exists</p>
    {% endif %}
    <div>
        <a href = "{% url 'encyclopedia:edit' title=title%}">Edit entry</a>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 class="font-italic">All Pages</h1>

    <ul>
        {% if message == False %}
        <p class="alert alert-info" role="alert">Here are some matched results</p>
        {% endif %}
        {% if entries != None %}
        {% for entry in entries %}
        <a href = "{% url 'encyclopedia:entry'  entry=entry%}"><li>{{ entry }}</li></a>
        {% endfor %}
        {% else %}
        <p  class="alert alert-info" role="alert">Page does Not exists</p>
        {% endif %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!DOCTYPE html>
<html land = "en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href = "{% static 'encylopedia/styles.css' %}", rel = "stylesheet">
    </head>
    <div class="row mx-auto font-italic"  style = "padding-top: 20px;padding-left: 20px;">
        <div class="sidebar col-lg-2 col-md-3">
            <h2 class="font-weight-bold">Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}", method = 'post'>
                {% csrf_token %}
                <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href = "{% url 'encyclopedia:create' %}">Create New Page</a> 
            </div>
            <div>
                <a href =  "{% url 'encyclopedia:random' %}">Random Page</a> 
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div style = "padding-top: 20px;padding-left: 100px;" class="font-italic main col-lg-10 col-md-9  margin-left:100px">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</html>

wiki/encyclopedia/templates/encyclopedia/layouts.html
{% load static %}
<!DOCTYPE html>
<html land = "en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href = "{% static 'encylopedia/styles.css' %}", rel = "stylesheet">
    </head>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}", method = 'post'>
                {% csrf_token %}
                <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href = "{% url 'encyclopedia:create' %}">Create New Page</a> 
            </div>
            <div>
                <a href =  "{% url 'encyclopedia:random' %}">Random Page</a> 
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div   class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</html>